"""Agregar campo is_active al modelo User

Revision ID: 496987ff9287
Revises: 
Create Date: 2025-04-15 23:13:34.511561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '496987ff9287'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
